### ISSUE TITLE
Want the code for Travelling sales man problem in java

### ISSUE THREAD

**Issue by sudhir-120901** [sudhir-120901/git.tut#2]

**Comment by utkr07** [comment]
Hello @sudhir-120901 
Can you please assign this issue to me? Thank you

**Comment by Prakhar9450** [comment]
please assign me the task

**Comment by RohitShah1706** [comment]
I have a good understanding of CP in C++ and Java. 
@sudhir-120901 please assign this issue to me.

**Comment by alokik0112** [comment]
@sudhir-120901  Assign this issue to me.

**Comment by sudhir-120901** [comment]
this fixes #2
